# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: dev
    groups:
      npm-dependencies:
        patterns: ["*"]
    ignore:
      - dependency-name: react
        versions: ["< 19.0.0"]
      - dependency-name: react-dom
        versions: ["< 19.0.0"]
      - dependency-name: "@clerk/remix"
        versions: ["< 4.0.0"]
      - dependency-name: "@clerk/themes"
        versions: ["< 2.0.0"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
