name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Build cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}

      - name: Install
        run: "pnpm install"

      - name: Build
        run: "pnpm exec turbo run build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "aspects-vtt"
          entrypoint: "server.ts"
          root: "."
          include: |
            build/**
            server.ts
            package.json
            deno.json
            deno.lock
