name: Prod Deploy PR

on:
  workflow_dispatch:
  push:
    branches:
      - dev

concurrency: dev-to-main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Deploy to Production
          body: Merge this PR to deploy to production.
          base: dev
          commit-message: "[ci] create prod deploy PR"
          delete-branch: false
