# https://github.com/peter-evans/create-pull-request/blob/v6/docs/examples.md#keep-a-branch-up-to-date-with-another
name: Prod Deploy PR

on:
  workflow_dispatch:
  push:
    branches:
      - dev

concurrency: dev-to-main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Reset branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Deploy to Production
          body: Merge this PR to deploy to production.
          branch: dev
          commit-message: "[ci] create prod deploy PR"
          delete-branch: false
